# Server configuration
server:
   port: 8886
   servlet:
      context-path: /notification
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: notification-service
   data:
      mongodb:
         uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/notification_service?authSource=admin}
   kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
         auto-offset-reset: earliest
         group-id: notification-service-group
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
         properties:
            spring.json.trusted.packages: "*"
            spring.json.value.default.type: "com.tth.commonlibrary.event.dto.NotificationEvent"

# Application configuration
app:
   services:
      email:
         url: ${EMAIL_SERVICE_URL:https://api.brevo.com}
         mail-api-key: ${MAIL_API_KEY}