# Server configuration
server:
   port: 8080
   servlet:
      context-path: /identity
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: identity-service
   datasource:
      url: ${DBMS_URL:jdbc:mysql://localhost:3306/identity_service}
      driverClassName: "com.mysql.cj.jdbc.Driver"
      username: ${DBMS_USERNAME:root}
      password: ${DBMS_PASSWORD:root}
   jpa:
      open-in-view: false
      hibernate:
         ddl-auto: update
   kafka:
      bootstrap-servers: localhost:9094
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

# JWT configuration
jwt:
   signer-key: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
   valid-duration: ${JWT_VALID_DURATION:3600} # in seconds
   refreshable-duration: ${JWT_REFRESHABLE_DURATION:86400} # in seconds

# Application configuration
app:
   services:
      outbound:
         identity:
            client-id: ${IDENTITY_CLIENT_ID:<clientId>}
            client-secret: ${IDENTITY_CLIENT_SECRET:<clientSecret>}
            grant-type: "authorization_code"
            redirect-uri: ${IDENTITY_REDIRECT_URI:http://localhost:8080/identity/login/oauth2/code/identity} # http://localhost:3000/authenticate
      profile:
         url: ${PROFILE_SERVICE_URL:http://localhost:8083/profile}
      file:
         url: ${FILE_SERVICE_URL:http://localhost:8886/file}
