server:
   port: 8080
   servlet:
      context-path: /identity
      encoding:
         charset: UTF-8
         enabled: true
         force: true

spring:
   application:
      name: identity-service
   datasource:
      url: ${DBMS_URL:jdbc:mysql://localhost:3306/identity_service}
      driverClassName: "com.mysql.cj.jdbc.Driver"
      username: ${DBMS_USERNAME:root}
      password: ${DBMS_PASSWORD:root}
   jpa:
      show-sql: true
      open-in-view: false
      hibernate:
         ddl-auto: update

jwt:
   signer-key: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
   valid-duration: ${JWT_VALID_DURATION:3600} # in seconds
   refreshable-duration: ${JWT_REFRESHABLE_DURATION:86400} # in seconds

outbound:
   identity:
      client-id: "<clientId>"
      client-secret: "<clientSecret>"
      grant-type: "authorization_code"
      redirect-uri: "http://localhost:3000/authenticate"
