name: hscms

networks:
   hscms-network:
      driver: bridge
      name: hscms-network

volumes:
   mysql:

services:
   #   nginx:
   #      image: 'nginx:1.25.3'
   #      restart: unless-stopped
   #      container_name: nginx
   #      ports:
   #         - "80:80"
   #      volumes:
   #         - ./docker/server/templates:/etc/nginx/templates
   #         - ./docker/server/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
   #      networks:
   #         - hscms-network
   kafka:
      image: 'bitnami/kafka:3.7.0'
      restart: unless-stopped
      hostname: kafka
      container_name: kafka
      ports:
         - '9094:9094'
      environment:
         - KAFKA_ENABLE_KRAFT=yes
         - KAFKA_CFG_PROCESS_ROLES=controller,broker
         - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
         - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
         - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.01:9094,EXTERNAL://localhost:9094
         - KAFKA_BROKER_ID=1
         - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
         - ALLOW_PLAINTEXT_LISTENER=yes
         - KAFKA_CFG_NODE_ID=1
         - KAFKA_KRAFT_CLUSTER_ID=hscms-kafka
         - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      healthcheck:
         test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9094" ]
         interval: 10s
         timeout: 5s
         retries: 5
      networks:
         - hscms-network
   mysql:
      image: 'mysql:8.0.39-debian'
      restart: unless-stopped
      hostname: mysql
      container_name: mysql
      ports:
         - '3306:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=root
      volumes:
         - ./docker/db/mysql_initial.sql:/docker-entrypoint-initdb.d/mysql_initial.sql
         - mysql:/var/lib/mysql
      networks:
         - hscms-network
   mongodb:
      image: 'bitnami/mongodb:7.0.11'
      restart: unless-stopped
      hostname: mongodb
      container_name: mongodb
      ports:
         - '27017:27017'
      environment:
         - MONGODB_ROOT_USER=root
         - MONGODB_ROOT_PASSWORD=root
      networks:
         - hscms-network
   neo4j:
      image: 'neo4j:latest'
      restart: unless-stopped
      hostname: neo4j
      container_name: neo4j
      ports:
         - '7474:7474'
         - '7687:7687'
      environment:
         - NEO4J_AUTH=neo4j/admin@123
      networks:
         - hscms-network
   #   hscms-keycloak:
   #      image: 'quay.io/keycloak/keycloak:25.0.0'
   #      restart: unless-stopped
   #      hostname: hscms-keycloak
   #      container_name: hscms-keycloak
   #      command: [ 'start-dev --import-realm' ]
   #      ports:
   #         - '8180:8080'
   #      environment:
   #         - KEYCLOAK_ADMIN=admin
   #         - KEYCLOAK_ADMIN_PASSWORD=admin
   #      networks:
   #         - hscms-network
   hscms-gateway:
      build: ./api-gateway
      image: ghcr.io/hiepthanhtran/hscms-gateway:latest
      restart: unless-stopped
      container_name: hscms-gateway
      ports:
         - '8888:8888'
      environment:
         - FILE_SERVICE_URL=http://hscms-file:8887
         - NOTIFICATION_SERVICE_URL=http://hscms-notification:8886
         - CART_SERVICE_URL=http://hscms-cart:8081
         - PROFILE_SERVICE_URL=http://hscms-profile:8082
         - IDENTITY_SERVICE_URL=http://hscms-identity:8083
         - PRODUCT_SERVICE_URL=http://hscms-product:8084
         - RATING_SERVICE_URL=http://hscms-rating:8085
         - INVENTORY_SERVICE_URL=http://hscms-inventory:8086
         - ORDER_SERVICE_URL=http://hscms-order:8087
         - SHIPPING_SERVICE_URL=http://hscms-shipping:8088
      networks:
         - hscms-network
   hscms-file:
      build: ./file-service
      image: ghcr.io/hiepthanhtran/hscms-file-service:latest
      restart: unless-stopped
      container_name: hscms-file
      ports:
         - '8887:8887'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
         - AWS_SECRET=${AWS_SECRET}
         - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      depends_on:
         - kafka
      networks:
         - hscms-network
   hscms-notification:
      build: ./notification-service
      image: ghcr.io/hiepthanhtran/hscms-notification-service:latest
      restart: unless-stopped
      container_name: hscms-notification
      ports:
         - '8886:8886'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - MAIL_API_KEY=${MAIL_API_KEY}
         - MONGODB_URI=mongodb://root:root@mongodb:27017/notification_service?authSource=admin
      #         - EMAIL_SERVICE_URL
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscms-network
   hscms-cart:
      build: ./cart-service
      image: ghcr.io/hiepthanhtran/hscms-cart-service:latest
      restart: unless-stopped
      container_name: hscms-cart
      ports:
         - '8081:8081'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - MONGODB_URI=mongodb://root:root@mongodb:27017/cart_service?authSource=admin
#         - PRODUCT_SERVICE_URL=http://hscms-product:8084
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscms-network
   hscms-profile:
      build: ./profile-service
      image: ghcr.io/hiepthanhtran/hscms-profile-service:latest
      restart: unless-stopped
      container_name: hscms-profile
      ports:
         - '8082:8082'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - NEO4J_URI=bolt://neo4j:7687
         - NEO4J_USERNAME=neo4j
         - NEO4J_PASSWORD=admin
      depends_on:
         - kafka
         - neo4j
      networks:
         - hscms-network
   hscms-identity:
      build: ./identity-service
      image: ghcr.io/hiepthanhtran/hscms-identity-service:latest
      restart: unless-stopped
      container_name: hscms-identity
      ports:
         - '8083:8083'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - DBMS_URL=jdbc:mysql://mysql:3306/identity_service
         - DBMS_USERNAME=root
         - DBMS_PASSWORD=root
#         - PROFILE_SERVICE_URL=http://hscms-profile:8082
#         - FILE_SERVICE_URL=http://hscms-file:8887
      #         - JWT_SIGNER_KEY
      #         - JWT_VALID_DURATION
      #         - JWT_REFRESHABLE_DURATION
      depends_on:
         - kafka
         - mysql
      networks:
         - hscms-network
   hscms-product:
      build: ./product-service
      image: ghcr.io/hiepthanhtran/hscms-product-service:latest
      restart: unless-stopped
      container_name: hscms-product
      ports:
         - '8084:8084'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - MONGODB_URI=mongodb://root:root@mongodb:27017/product_service?authSource=admin
#         - PROFILE_SERVICE_URL=http://hscms-profile:8082
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscms-network
   hscms-rating:
      build: ./rating-service
      image: ghcr.io/hiepthanhtran/hscms-rating-service:latest
      restart: unless-stopped
      container_name: hscms-rating
      ports:
         - '8085:8085'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - MONGODB_URI=mongodb://root:root@mongodb:27017/rating_service?authSource=admin
#         - PROFILE_SERVICE_UR= http://hscms-profile:8082
#         - IDENTITY_SERVICE_URL=http://hscms-identity:8083
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscms-network
   hscms-inventory:
      build: ./inventory-service
      image: ghcr.io/hiepthanhtran/hscms-inventory-service:latest
      restart: unless-stopped
      container_name: hscms-inventory
      ports:
         - '8086:8086'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - DBMS_URL=jdbc:mysql://mysql:3306/inventory_service
         - DBMS_USERNAME=root
         - DBMS_PASSWORD=root
#         - PRODUCT_SERVICE_URL=http://hscms-product:8084
      depends_on:
         - kafka
         - mysql
      networks:
         - hscms-network
   hscms-order:
      build: ./order-service
      image: ghcr.io/hiepthanhtran/hscms-order-service:latest
      restart: unless-stopped
      container_name: hscms-order
      ports:
         - '8087:8087'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - DBMS_URL=jdbc:mysql://mysql:3306/order_service
         - DBMS_USERNAME=root
         - DBMS_PASSWORD=root
         - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
#         - IDENTITY_SERVICE_URL=http://hscms-identity:8083
#         - PRODUCT_SERVICE_URL=http://hscms-product:8084
#         - INVENTORY_SERVICE_URL=http://hscms-inventory:8086
      depends_on:
         - kafka
         - mysql
      networks:
         - hscms-network
   hscms-shipping:
      build: ./shipping-service
      image: ghcr.io/hiepthanhtran/hscms-shipping-service:latest
      restart: unless-stopped
      container_name: hscms-shipping
      ports:
         - '8088:8088'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
         - MONGODB_URI=mongodb://root:root@mongodb:27017/shipping_service?authSource=admin
#         - IDENTITY_SERVICE_URL=http://hscms-identity:8083
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscms-network