name: scms

networks:
   scms-network:
      driver: bridge
      name: scms-network

volumes:
   mysql:

services:
   #   nginx:
   #      image: 'nginx:1.25.3'
   #      restart: unless-stopped
   #      hostname: nginx
   #      container_name: nginx
   #      ports:
   #         - "80:80"
   #      volumes:
   #         - ./docker/nginx/templates:/etc/nginx/templates
   #         - ./docker/nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
   #      networks:
   #         - scms-network
   kafka:
      image: 'bitnami/kafka:3.7.0'
      container_name: kafka
      hostname: kafka
      ports:
         - '9094:9094'
      environment:
         - KAFKA_CFG_NODE_ID=0
         - KAFKA_CFG_PROCESS_ROLES=controller,broker
         - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
         - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
         - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
         - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      networks:
         - scms-network
   swagger-ui:
      image: 'swaggerapi/swagger-ui:v4.16.0'
      restart: unless-stopped
      hostname: swagger-ui
      container_name: swagger-ui
      environment:
         - BASE_URL=/swagger-ui
         - URLS
         - OAUTH_CLIENT_ID=swagger-ui
         - OAUTH_USE_PKCE=true
      networks:
         - scms-network
   #   phpmyadmin:
   #      image: 'phpmyadmin/phpmyadmin:5.1.1'
   #      restart: unless-stopped
   #      hostname: phpmyadmin
   #      container_name: phpmyadmin
   #      ports:
   #         - '8090:81'
   #      environment:
   #         - PMA_HOST=mysql
   #         - MYSQL_ROOT_PASSWORD=root
   #      depends_on:
   #         -  mysql
   #      networks:
   #         - scms-network
   mysql:
      image: 'mysql:8.0.39-debian'
      restart: unless-stopped
      hostname: mysql
      container_name: mysql
      ports:
         - '3306:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=root
      volumes:
         - ./docker/db/mysql_initial.sql:/docker-entrypoint-initdb.d/mysql_initial.sql
         - mysql:/var/lib/mysql
      networks:
         - scms-network
   mongodb:
      image: 'bitnami/mongodb:7.0.11'
      restart: unless-stopped
      hostname: mongodb
      container_name: mongodb
      ports:
         - '27017:27017'
      environment:
         - MONGODB_ROOT_USER=root
         - MONGODB_ROOT_PASSWORD=root
      networks:
         - scms-network
   neo4j:
      image: 'neo4j:latest'
      restart: unless-stopped
      hostname: neo4j
      container_name: neo4j
      ports:
         - '7474:7474'
         - '7687:7687'
      environment:
         - NEO4J_AUTH=neo4j/admin@123
      networks:
         - scms-network