version: "3"
services:
   mysql:
      image: 'mysql:8.0.39-debian'
      container_name: mysql-8.0.39-debian
      hostname: mysql
      ports:
         - '3306:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=root
   mongodb:
      image: 'bitnami/mongodb:7.0.11'
      container_name: mongodb-7.0.11
      hostname: mongo
      ports:
         - '27017:27017'
      environment:
         - MONGODB_ROOT_USER=root
         - MONGODB_ROOT_PASSWORD=root
   neo4j:
      image: 'neo4j:latest'
      container_name: neo4j-latest
      hostname: neo4j
      ports:
         - '7474:7474'
         - '7687:7687'
      environment:
         - NEO4J_AUTH=neo4j/admin@123
   kafka:
      image: 'bitnami/kafka:3.7.0'
      container_name: kafka-3.7.0
      hostname: kafka
      ports:
         - '9094:9094'
      environment:
         - KAFKA_CFG_NODE_ID=0
         - KAFKA_CFG_PROCESS_ROLES=controller,broker
         - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
         - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
         - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
         - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
