name: scms

networks:
   scms-network:
      driver: bridge
      name: scms-network

volumes:
   mysql:

services:
   #   nginx:
   #      image: 'nginx:1.25.3'
   #      restart: unless-stopped
   #      hostname: nginx
   #      container_name: nginx
   #      ports:
   #         - "80:80"
   #      volumes:
   #         - ./docker/nginx/templates:/etc/nginx/templates
   #         - ./docker/nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
   #      networks:
   #         - scms-network
   zookeeper:
      image: 'confluentinc/cp-zookeeper:6.2.1'
      restart: unless-stopped
      hostname: zookeeper
      container_name: zookeeper
      environment:
         - ZOOKEEPER_CLIENT_PORT=2181
         - ZOOKEEPER_ADMIN_ENABLE_SERVER=false
      networks:
         - scms-network
   kafka:
      image: 'confluentinc/cp-kafka:6.2.1'
      restart: unless-stopped
      hostname: kafka
      container_name: kafka
      ports:
         - 9092:9092
      environment:
         - KAFKA_BROKER_ID=0
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
         - KAFKA_NUM_PARTITIONS=12
         - KAFKA_COMPRESSION_TYPE=gzip
         - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
         - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
         - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
         - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
         - KAFKA_JMX_PORT=9091
         - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
         - KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.auth.SimpleAclAuthorizer
         - KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      links:
         - zookeeper
      networks:
         - scms-network
   swagger-ui:
      image: 'swaggerapi/swagger-ui:v4.16.0'
      restart: unless-stopped
      hostname: swagger-ui
      container_name: swagger-ui
      environment:
         - BASE_URL=/swagger-ui
         - URLS
         - OAUTH_CLIENT_ID=swagger-ui
         - OAUTH_USE_PKCE=true
      networks:
         - scms-network
   #   phpmyadmin:
   #      image: 'phpmyadmin/phpmyadmin:5.1.1'
   #      restart: unless-stopped
   #      hostname: phpmyadmin
   #      container_name: phpmyadmin
   #      ports:
   #         - '8090:81'
   #      environment:
   #         - PMA_HOST=mysql
   #         - MYSQL_ROOT_PASSWORD=root
   #      depends_on:
   #         -  mysql
   #      networks:
   #         - scms-network
   mysql:
      image: 'mysql:8.0.39-debian'
      restart: unless-stopped
      hostname: mysql
      container_name: mysql
      ports:
         - '3306:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=root
      volumes:
         - ./docker/db/mysql_initial.sql:/docker-entrypoint-initdb.d/mysql_initial.sql
         - mysql:/var/lib/mysql
      networks:
         - scms-network
   mongodb:
      image: 'bitnami/mongodb:7.0.11'
      restart: unless-stopped
      hostname: mongodb
      container_name: mongodb
      ports:
         - '27017:27017'
      environment:
         - MONGODB_ROOT_USER=root
         - MONGODB_ROOT_PASSWORD=root
      networks:
         - scms-network
   neo4j:
      image: 'neo4j:latest'
      restart: unless-stopped
      hostname: neo4j
      container_name: neo4j
      ports:
         - '7474:7474'
         - '7687:7687'
      environment:
         - NEO4J_AUTH=neo4j/admin@123
      networks:
         - scms-network
   #   scms-keycloak:
   #      image: 'quay.io/keycloak/keycloak:25.0.0'
   #      restart: unless-stopped
   #      hostname: scms-keycloak
   #      container_name: scms-keycloak
   #      command: [ 'start-dev --import-realm' ]
   #      ports:
   #         - '8180:8080'
   #      environment:
   #         - KEYCLOAK_ADMIN=admin
   #         - KEYCLOAK_ADMIN_PASSWORD=admin
   #      networks:
   #         - scms-network
   scms-gateway:
      build: ./api-gateway
      image: ghcr.io/hiepthanhtran/scms-gateway:latest
      restart: unless-stopped
      hostname: scms-gateway
      container_name: scms-gateway
      ports:
         - '8888:8888'
      environment:
         - IDENTITY_BASE_URL=http://scms-identity:8083
         - FILE_SERVICE_URL=http://scms-file:8887
         - NOTIFICATION_SERVICE_URL=http://scms-notification:8886
         - CART_SERVICE_URL=http://scms-cart:8081
         - PROFILE_SERVICE_URL=http://scms-profile:8082
         - IDENTITY_SERVICE_URL=http://scms-identity:8083
         - PRODUCT_SERVICE_URL=http://scms-product:8084
         - RATING_SERVICE_URL=http://scms-rating:8085
         - INVENTORY_SERVICE_URL=http://scms-inventory:8086
         - ORDER_SERVICE_URL=http://scms-order:8087
         - SHIPPING_SERVICE_URL=http://scms-shipping:8088
      networks:
         - scms-network
   scms-file:
      build: ./file-service
      image: ghcr.io/hiepthanhtran/scms-file:latest
      restart: unless-stopped
      hostname: scms-file
      container_name: scms-file
      ports:
         - '8887:8887'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
         - AWS_SECRET=${AWS_SECRET}
         - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      depends_on:
         - kafka
      networks:
         - scms-network
   scms-notification:
      build: ./notification-service
      image: ghcr.io/hiepthanhtran/scms-notification:latest
      restart: unless-stopped
      hostname: scms-notification
      container_name: scms-notification
      ports:
         - '8886:8886'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - MAIL_API_KEY=${MAIL_API_KEY}
         - MONGODB_URI=mongodb://root:root@mongodb:27017/notification_service?authSource=admin
      #         - EMAIL_SERVICE_URL
      depends_on:
         - kafka
         - mongodb
      networks:
         - scms-network
   scms-cart:
      build: ./cart-service
      image: ghcr.io/hiepthanhtran/scms-cart:latest
      restart: unless-stopped
      hostname: scms-cart
      container_name: scms-cart
      ports:
         - '8081:8081'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - MONGODB_URI=mongodb://root:root@mongodb:27017/cart_service?authSource=admin
         - PRODUCT_SERVICE_URL=http://scms-product:8084/product
      depends_on:
         - kafka
         - mongodb
      networks:
         - scms-network
   scms-profile:
      build: ./profile-service
      image: ghcr.io/hiepthanhtran/scms-profile:latest
      restart: unless-stopped
      hostname: scms-profile
      container_name: scms-profile
      ports:
         - '8082:8082'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - NEO4J_URI=bolt://neo4j:7687
         - NEO4J_USERNAME=neo4j
         - NEO4J_PASSWORD=admin@123
      depends_on:
         - kafka
         - neo4j
      networks:
         - scms-network
   scms-identity:
      build: ./identity-service
      image: ghcr.io/hiepthanhtran/scms-identity:latest
      restart: unless-stopped
      hostname: scms-identity
      container_name: scms-identity
      ports:
         - '8083:8083'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - DBMS_URL=jdbc:mysql://mysql:3306/identity_service
         - DBMS_USERNAME=root
         - DBMS_PASSWORD=root
         - PROFILE_SERVICE_URL=http://scms-profile:8082/profile
         - FILE_SERVICE_URL=http://scms-file:8887/file
      #         - JWT_SIGNER_KEY
      #         - JWT_VALID_DURATION
      #         - JWT_REFRESHABLE_DURATION
      depends_on:
         - kafka
         - mysql
      networks:
         - scms-network
   scms-product:
      build: ./product-service
      image: ghcr.io/hiepthanhtran/scms-product:latest
      restart: unless-stopped
      hostname: scms-product
      container_name: scms-product
      ports:
         - '8084:8084'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - MONGODB_URI=mongodb://root:root@mongodb:27017/product_service?authSource=admin
         - PROFILE_SERVICE_URL=http://scms-profile:8082/profile
      depends_on:
         - kafka
         - mongodb
      networks:
         - scms-network
   scms-rating:
      build: ./rating-service
      image: ghcr.io/hiepthanhtran/scms-rating:latest
      restart: unless-stopped
      hostname: scms-rating
      container_name: scms-rating
      ports:
         - '8085:8085'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - MONGODB_URI=mongodb://root:root@mongodb:27017/rating_service?authSource=admin
         - PROFILE_SERVICE_UR= http://scms-profile:8082/profile
         - IDENTITY_SERVICE_URL=http://scms-identity:8083/identity
      depends_on:
         - kafka
         - mongodb
      networks:
         - scms-network
   scms-inventory:
      build: ./inventory-service
      image: ghcr.io/hiepthanhtran/scms-inventory:latest
      restart: unless-stopped
      hostname: scms-inventory
      container_name: scms-inventory
      ports:
         - '8086:8086'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - DBMS_URL=jdbc:mysql://mysql:3306/inventory_service
         - DBMS_USERNAME=root
         - DBMS_PASSWORD=root
         - PRODUCT_SERVICE_URL=http://scms-product:8084/product
      depends_on:
         - kafka
         - mysql
      networks:
         - scms-network
   scms-order:
      build: ./order-service
      image: ghcr.io/hiepthanhtran/scms-order:latest
      restart: unless-stopped
      hostname: scms-order
      container_name: scms-order
      ports:
         - '8087:8087'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - DBMS_URL=jdbc:mysql://mysql:3306/order_service
         - DBMS_USERNAME=root
         - DBMS_PASSWORD=root
         - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
         - IDENTITY_SERVICE_URL=http://scms-identity:8083/identity
         - PRODUCT_SERVICE_URL=http://scms-product:8084/product
         - INVENTORY_SERVICE_URL=http://scms-inventory:8086/inventory
      depends_on:
         - kafka
         - mysql
      networks:
         - scms-network
   scms-shipping:
      build: ./shipping-service
      image: ghcr.io/hiepthanhtran/scms-shipping:latest
      restart: unless-stopped
      hostname: scms-shipping
      container_name: scms-shipping
      ports:
         - '8088:8088'
      environment:
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - MONGODB_URI=mongodb://root:root@mongodb:27017/shipping_service?authSource=admin
         - IDENTITY_SERVICE_URL=http://scms-identity:8083/identity
      depends_on:
         - kafka
         - mongodb
      networks:
         - scms-network