name: hscm

networks:
   hscm-network:
      driver: bridge
      name: hscm-network

volumes:
   mysql:

services:
   #   nginx:
   #      image: 'nginx:1.25.3'
   #      restart: unless-stopped
   #      container_name: hscm-nginx
   #      ports:
   #         - "80:80"
   #      volumes:
   #         - ./docker/server/templates:/etc/nginx/templates
   #         - ./docker/server/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
   #      networks:
   #         - hscm-network
   # kafka:
   #  image: 'bitnami/kafka:3.7.0'
   #  container_name: kafka
   #  hostname: kafka
   #  ports:
   #    - '9094:9094'
   #  environment:
   #    - KAFKA_CFG_NODE_ID=0
   #    - KAFKA_CFG_PROCESS_ROLES=controller,broker
   #    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
   #    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
   #    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
   #    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
   #    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
   #    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
   # networks:
   #    - hscm-network
   zookeeper:
      image: 'confluentinc/cp-zookeeper:latest'
      container_name: hscm-zookeeper
      ports:
         - "22181:2181"
      environment:
         - ZOOKEEPER_SERVER_ID=1
         - ZOOKEEPER_CLIENT_PORT=2181
         - ZOOKEEPER_TICK_TIME=2000
      networks:
         - hscm-network
   kafka:
      image: 'confluentinc/cp-kafka:latest'
      container_name: hscm-kafka
      ports:
         - "9094:9094"
      environment:
         - KAFKA_BROKER_ID=1
         - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
         - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9094
         - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
         - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
         - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTO=1
      depends_on:
         - zookeeper
      networks:
         - hscm-network
   mysql:
      image: 'mysql:8.0.39-debian'
      hostname: mysql
      container_name: hscm-mysql
      ports:
         - '3306:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=root
      volumes:
         - ./docker/db/mysql_initial.sql:/docker-entrypoint-initdb.d/mysql_initial.sql
         - mysql:/var/lib/mysql
      networks:
         - hscm-network
   mongodb:
      image: 'bitnami/mongodb:7.0.11'
      hostname: mongodb
      container_name: hscm-mongodb
      ports:
         - '27017:27017'
      environment:
         - MONGODB_ROOT_USER=root
         - MONGODB_ROOT_PASSWORD=root
      networks:
         - hscm-network
   neo4j:
      image: 'neo4j:latest'
      hostname: neo4j
      container_name: hscm-neo4j
      ports:
         - '7474:7474'
         - '7687:7687'
      environment:
         - NEO4J_AUTH=neo4j/admin@123
      networks:
         - hscm-network
   #   hscm-keycloak:
   #      image: 'quay.io/keycloak/keycloak:25.0.0'
   #      hostname: hscm-keycloak
   #      container_name: hscm-keycloak
   #      command: [ 'start-dev --import-realm' ]
   #      ports:
   #         - '8180:8080'
   #      environment:
   #         - KEYCLOAK_ADMIN=admin
   #         - KEYCLOAK_ADMIN_PASSWORD=admin
   #      networks:
   #         - hscm-network
   hscm-cart:
      build: ./cart-service
      image: ghcr.io/hiepthanhtran/hscm-cart-service:latest
      container_name: hscm-cart
      ports:
         - '8081:8081'
      environment:
         - MONGODB_URI=mongodb://root:root@mongodb:27017/cart_service?authSource=admin
      #         - PRODUCT_SERVICE_URL
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscm-network
   hscm-profile:
      build: ./profile-service
      image: ghcr.io/hiepthanhtran/hscm-profile-service:latest
      container_name: hscm-profile
      ports:
         - '8082:8082'
      #      environment:
      #         - NEO4J_URI
      #         - NEO4J_USERNAME
      #         - NEO4J_PASSWORD
      depends_on:
         - kafka
         - neo4j
      networks:
         - hscm-network
   hscm-identity:
      build: ./identity-service
      image: ghcr.io/hiepthanhtran/hscm-identity-service:latest
      container_name: hscm-identity
      ports:
         - '8083:8083'
      environment:
         - DBMS_URL=jdbc:mysql://mysql:3306/identity_service
      #         - DBMS_USERNAME
      #         - DBMS_PASSWORD
      #         - JWT_SIGNER_KEY
      #         - JWT_VALID_DURATION
      #         - JWT_REFRESHABLE_DURATION
      #         - IDENTITY_CLIENT_ID
      #         - IDENTITY_CLIENT_SECRET
      #         - IDENTITY_REDIRECT_URI
      #         - PROFILE_SERVICE_URL
      #         - FILE_SERVICE_URL
      depends_on:
         - kafka
         - mysql
      networks:
         - hscm-network
   hscm-product:
      build: ./product-service
      image: ghcr.io/hiepthanhtran/hscm-product-service:latest
      container_name: hscm-product
      ports:
         - '8084:8084'
      environment:
         - MONGODB_URI=mongodb://root:root@mongodb:27017/product_service?authSource=admin
      #         - PROFILE_SERVICE_URL
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscm-network
   hscm-rating:
      build: ./rating-service
      image: ghcr.io/hiepthanhtran/hscm-rating-service:latest
      container_name: hscm-rating
      ports:
         - '8085:8085'
      environment:
         - MONGODB_URI=mongodb://root:root@mongodb:27017/rating_service?authSource=admin
      #         - IDENTITY_SERVICE_URL
      #         - PROFILE_SERVICE_URL
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscm-network
   hscm-inventory:
      build: ./inventory-service
      image: ghcr.io/hiepthanhtran/hscm-inventory-service:latest
      container_name: hscm-inventory
      ports:
         - '8086:8086'
      environment:
         - DBMS_URL=jdbc:mysql://mysql:3306/inventory_service
      #         - DBMS_USERNAME
      #         - DBMS_PASSWORD
      #         - PRODUCT_SERVICE_URL
      depends_on:
         - kafka
         - mysql
      networks:
         - hscm-network
   hscm-order:
      build: ./order-service
      image: ghcr.io/hiepthanhtran/hscm-order-service:latest
      container_name: hscm-order
      ports:
         - '8087:8087'
      environment:
         - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
         - DBMS_URL=jdbc:mysql://mysql:3306/order_service
      #         - DBMS_USERNAME
      #         - DBMS_PASSWORD
      #         - IDENTITY_SERVICE_URL
      #         - PRODUCT_SERVICE_URL
      #         - INVENTORY_SERVICE_URL
      depends_on:
         - kafka
         - mysql
      networks:
         - hscm-network
   hscm-shipping:
      build: ./shipping-service
      image: ghcr.io/hiepthanhtran/hscm-shipping-service:latest
      container_name: hscm-shipping
      ports:
         - '8088:8088'
      environment:
         - MONGODB_URI=mongodb://root:root@mongodb:27017/shipping_service?authSource=admin
         - IDENTITY_SERVICE_URL
      depends_on:
         - kafka
         - mysql
      networks:
         - hscm-network
   hscm-notification:
      build: ./notification-service
      image: ghcr.io/hiepthanhtran/hscm-notification-service:latest
      container_name: hscm-notification
      ports:
         - '8886:8886'
      environment:
         - MAIL_API_KEY=${MAIL_API_KEY}
         - MONGODB_URI=mongodb://root:root@mongodb:27017/notification_service?authSource=admin
      #         - EMAIL_SERVICE_URL
      depends_on:
         - kafka
         - mongodb
      networks:
         - hscm-network
   hscm-file:
      build: ./file-service
      image: ghcr.io/hiepthanhtran/hscm-file-service:latest
      container_name: hscm-file
      ports:
         - '8887:8887'
      environment:
         - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
         - AWS_SECRET=${AWS_SECRET}
         - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      depends_on:
         - kafka
      networks:
         - hscm-network
   hscm-api-gateway:
      build: ./api-gateway
      image: ghcr.io/hiepthanhtran/hscm-api-gateway:latest
      container_name: hscm-api-gateway
      ports:
         - '8888:8888'
      #      environment:
      #         - IDENTITY_SERVICE_URL
      #         - FILE_SERVICE_URL
      #         - NOTIFICATION_SERVICE_URL
      #         - SHIPPING_SERVICE_URL
      #         - PROFILE_SERVICE_URL
      #         - IDENTITY_SERVICE_URL
      #         - PRODUCT_SERVICE_URL
      #         - SHIPPING_SERVICE_URL
      #         - SHIPPING_SERVICE_URL
      #         - ORDER_SERVICE_URL
      #         - SHIPPING_SERVICE_URL
      depends_on:
         - kafka
      networks:
         - hscm-network