# Server configuration
server:
   port: 8888
   servlet:
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Application configuration
app:
   api-prefix: /api/v1
   strip-prefix: 2
   services:
      indentity:
         url: ${IDENTITY_SERVICE_URL:http://localhost:8083/identity}

# Spring configuration
spring:
   application:
      name: api-gateway
   cloud:
      gateway:
         routes:
            -  id: file_service
               uri: ${FILE_SERVICE_URL:http://localhost:8887}
               predicates:
                  - Path=${app.api-prefix}/file/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: notification_service
               uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8886}
               predicates:
                  - Path=${app.api-prefix}/notification/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: cart_service
               uri: ${CART_SERVICE_URL:http://localhost:8081}
               predicates:
                  - Path=${app.api-prefix}/cart/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: profile_service
               uri: ${PROFILE_SERVICE_URL:http://localhost:8082}
               predicates:
                  - Path=${app.api-prefix}/profile/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: identity_service
               uri: ${IDENTITY_SERVICE_URL:http://localhost:8083}
               predicates:
                  - Path=${app.api-prefix}/identity/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: product_service
               uri: ${PRODUCT_SERVICE_URL:http://localhost:8084}
               predicates:
                  - Path=${app.api-prefix}/product/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: rating_service
               uri: ${RATING_SERVICE_URL:http://localhost:8085}
               predicates:
                  - Path=${app.api-prefix}/rating/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: inventory_service
               uri: ${INVENTORY_SERVICE_URL:http://localhost:8086}
               predicates:
                  - Path=${app.api-prefix}/inventory/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: order_service
               uri: ${ORDER_SERVICE_URL:http://localhost:8087}
               predicates:
                  - Path=${app.api-prefix}/order/**
               filters:
                  - StripPrefix=${app.strip-prefix}

            -  id: shipping_service
               uri: ${SHIPPING_SERVICE_URL:http://localhost:8088}
               predicates:
                  - Path=${app.api-prefix}/shipping/**
               filters:
                  - StripPrefix=${app.strip-prefix}