# Server configuration
server:
   port: 8888
   servlet:
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Application configuration
app:
   api-prefix: /api/v1
   strip-prefix: 2
   services:
      indentity:
         url: http://localhost:8080/identity

# Spring configuration
spring:
   application:
      name: api-gateway
   cloud:
      gateway:
         routes:
            -  id: identity_service
               uri: http://localhost:8080
               predicates:
                  - Path=${app.api-prefix}/identity/**
               filters:
                  - StripPrefix=${app.strip-prefix}
            -  id: file_service
               uri: http://localhost:8886
               predicates:
                  - Path=${app.api-prefix}/file/**
               filters:
                  - StripPrefix=${app.strip-prefix}
            -  id: notification_service
               uri: http://localhost:8887
               predicates:
                  - Path=${app.api-prefix}/notification/**
               filters:
                  - StripPrefix=${app.strip-prefix}
