# Server configuration
server:
   port: 8084
   servlet:
      context-path: /shipping
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: shipping-service
   data:
      mongodb:
         uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/shipping_service?authSource=admin}
   kafka:
      bootstrap-servers: localhost:9094
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

# Application configuration
app:
   services:
      identity:
         url: ${IDENTITY_SERVICE_URL:http://localhost:8080/identity}
