# Server configuration
server:
   port: 8085
   servlet:
      context-path: /rating
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: rating-service
   data:
      mongodb:
         uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/rating_service?authSource=admin}

# Application configuration
app:
   services:
      identity:
         url: ${IDENTITY_SERVICE_URL:http://localhost:8083/identity}
      profile:
         url: ${PROFILE_SERVICE_URL:http://localhost:8082/profile}