# Server configuration
server:
   port: 8887
   servlet:
      context-path: /file
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: file-service
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

# Application configuration
app:
   services:
      aws:
         access-key-id: ${AWS_ACCESS_KEY_ID}
         secret-access-key: ${AWS_SECRET}
         s3:
            bucket-name: ${S3_BUCKET_NAME}