# Server configuration
server:
   port: 8886
   servlet:
      context-path: /file
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: file-service
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

# AWS configuration
aws:
   access-key-id: AKIA6K5V7JXAJRAGPNOP
   secret-access-key: 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
   s3:
      bucket-name: harmony-supply-chain
