# Server configuration
server:
   port: 8084
   servlet:
      context-path: /product
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: product-service
   data:
      mongodb:
         uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/product_service?authSource=admin}
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

# Application configuration
app:
   services:
      profile:
         url: ${PROFILE_SERVICE_URL:http://localhost:8082/profile}