# Server configuration
server:
   port: 8084
   servlet:
      context-path: /product
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: product-service
   data:
      mongodb:
         uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/product_service?authSource=admin}
   kafka:
      bootstrap-servers: PLAINTEXT://kafka:9094
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
         auto-offset-reset: earliest
         group-id: product-service-group
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
         properties:
            spring.json.trusted.packages: "*"
            spring.json.value.default.type: "com.tth.event.dto.NotificationEvent"
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB

# Application configuration
app:
   services:
      profile:
         url: ${PROFILE_SERVICE_URL:http://localhost:8082/profile}