# Server configuration
server:
   port: 8081
   servlet:
      context-path: /cart
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: cart-service
   data:
      mongodb:
         uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/cart_service?authSource=admin}

# Application configuration
app:
   services:
      product:
         url: ${PRODUCT_SERVICE_URL:http://localhost:8084/product}