# Server configuration
server:
   servlet:
      context-path: /cart
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: common-library