# Server configuration
server:
   servlet:
      context-path: /common-library
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: common-library
